### ISSUE TITLE
KeyError: 'locations'

### ISSUE THREAD

**Issue by samuelyutt** [tsunglung/OpenCWB#15]
System Info:
Core 2024.12.2
Supervisor 2024.11.4
Operating System 14.0

Error Logs:
自行安裝整合產生錯誤。

記錄器: custom_components.opencwb.weather_update_coordinator
來源: helpers/update_coordinator.py:379
整合: OpenCWA (相關文件, 問題)
首次發生: 上午1:16:31 (376 事件)
最後紀錄: 上午9:34:54

Unexpected error fetching opencwb data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opencwb/weather_update_coordinator.py", line 96, in _async_update_data
    weather_response = await self._get_ocwb_weather()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opencwb/weather_update_coordinator.py", line 109, in _get_ocwb_weather
    weather = await self.hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/opencwb/core/weatherapi12/weather_manager.py", line 587, in one_call
    return one_call.OneCall.from_dict(json_data)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/config/custom_components/opencwb/core/weatherapi12/one_call.py", line 73, in from_dict
    the_dict = OpendataCWB.to_dict(the_dict)
  File "/config/custom_components/opencwb/core/utils/opendata_cwb.py", line 181, in to_dict
    for i in the_dict["records"]["locations"]:
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'locations'

**Comment by samuelyutt** [comment]
Fixed in d345c0cc8dd61d8ba7af9b0392fc31810bf5b370
