### ISSUE TITLE
KeyError: 'Impossible to read geographical coordinates from JSON'

### ISSUE THREAD

**Issue by samuelyutt** [tsunglung/OpenCWB#17]
自行安裝整合產生錯誤。

記錄器: custom_components.opencwb.weather_update_coordinator
來源: helpers/update_coordinator.py:379
整合: OpenCWA (相關文件, 問題)
首次發生: 上午1:10:56 (867 事件)
最後紀錄: 下午8:26:49

Unexpected error fetching opencwb data
Traceback (most recent call last):
  File "/config/custom_components/opencwb/core/weatherapi12/observation.py", line 79, in from_dict
    place = location.Location.from_dict(the_dict)
  File "/config/custom_components/opencwb/core/weatherapi12/location.py", line 90, in from_dict
    raise KeyError("Impossible to read geographical coordinates from JSON")
KeyError: 'Impossible to read geographical coordinates from JSON'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opencwb/weather_update_coordinator.py", line 96, in _async_update_data
    weather_response = await self._get_ocwb_weather()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opencwb/weather_update_coordinator.py", line 117, in _get_ocwb_weather
    weather = await self.hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_legacy_weather_and_forecast
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/opencwb/weather_update_coordinator.py", line 126, in _get_legacy_weather_and_forecast
    weather = self._ocwb_client.weather_at_place(
        self._location_name, interval)
  File "/config/custom_components/opencwb/core/weatherapi12/weather_manager.py", line 87, in weather_at_place
    return observation.Observation.from_dict(json_data)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/config/custom_components/opencwb/core/weatherapi12/observation.py", line 81, in from_dict
    raise exceptions.ParseAPIResponseError(
                              ''.join([__name__, ': impossible to read location info from JSON data']))
custom_components.opencwb.core.commons.exceptions.ParseAPIResponseError: custom_components.opencwb.core.weatherapi12.observation: impossible to read location info from JSON data

**Comment by tsunglung** [comment]
Which location name you use?

**Comment by FawenYo** [comment]
Same error here. I tried with "臺北市信義區", and here is the detailed error log

```
2024-12-19 14:58:26.288 ERROR (MainThread) [custom_components.opencwb.weather_update_coordinator] Unexpected error fetching opencwb data
Traceback (most recent call last):
  File "/config/custom_components/opencwb/core/weatherapi12/observation.py", line 79, in from_dict
    place = location.Location.from_dict(the_dict)
  File "/config/custom_components/opencwb/core/weatherapi12/location.py", line 90, in from_dict
    raise KeyError("Impossible to read geographical coordinates from JSON")
KeyError: 'Impossible to read geographical coordinates from JSON'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opencwb/weather_update_coordinator.py", line 96, in _async_update_data
    weather_response = await self._get_ocwb_weather()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opencwb/weather_update_coordinator.py", line 117, in _get_ocwb_weather
    weather = await self.hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_legacy_weather_and_forecast
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/opencwb/weather_update_coordinator.py", line 126, in _get_legacy_weather_and_forecast
    weather = self._ocwb_client.weather_at_place(
        self._location_name, interval)
  File "/config/custom_components/opencwb/core/weatherapi12/weather_manager.py", line 87, in weather_at_place
    return observation.Observation.from_dict(json_data)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/config/custom_components/opencwb/core/weatherapi12/observation.py", line 81, in from_dict
    raise exceptions.ParseAPIResponseError(
                              ''.join([__name__, ': impossible to read location info from JSON data']))
custom_components.opencwb.core.commons.exceptions.ParseAPIResponseError: custom_components.opencwb.core.weatherapi12.observation: impossible to read location info from JSON data
```

**Comment by samuelyutt** [comment]
> Which location name you use?

新竹市東區

By the way, the previous commit 9a3398f4c30b05029ea1d61e100afe9a59b8500a was available.
Anyway, thanks a lot for your work!👍

**Comment by tsunglung** [comment]
Which mode you use? Onecall or not?

**Comment by samuelyutt** [comment]
> Which mode you use? Onecall or not?

I forgot how I set the mode and couldn't find the configuration anywhere. Is there any hint to know which mode I'm using?

**Comment by FawenYo** [comment]
The issue was solved for me. I tested with "onecall_hourly" and now it works.

**Comment by tsunglung** [comment]
> > Which mode you use? Onecall or not?
> 
> I forgot how I set the mode and couldn't find the configuration anywhere. Is there any hint to know which mode I'm using?

From the log, you are not use OneCall.
I tested four mode without any problems. 
Did you use the latest code?

**Comment by samuelyutt** [comment]
I redownloaded the code again today and found out that onecall_hourly and one_daily is available, but the other two modes still have the same error.

**Comment by tsunglung** [comment]
Only few location name cause this error. Please update to the latest commit.

**Comment by samuelyutt** [comment]
The latest update fixed the error! So grateful for your time to fix this issue. Thanks a lot 🙏
